services:
  react-app:
    image: lastercho/flatsmoney:3.3.4
    container_name: flatsmoney
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - VITE_API_BASE_URL=https://flatback.mandini.eu/api
