services:
  react-app:
    image: lastercho/flatsmoney:1.3.0
    container_name: flatsmoney
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
