
services:
  react-app:
    image: lastercho/flatsmoney:1.2.1
    container_name: flatsmoney
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      # - VITE_API_BASE_URL=http://78.130.247.222:5000/api